---
title: "git_01"
author: "Rashonda Weathersby"
date: "February 04, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Once upon a midnight dreary, while I pondered, weak and weary, 

Over many a quaint and curious volume of forgotten lore-

While I nodded, nearly napping, suddenly there came a tapping, 

As of some one gently rapping, rapping at my chamber door.

"Tis some visitor," I muttered, "tapping at my chamber door-

Only this and nothing more."


Ah, distinctly I remember it was in the bleak December;

And each separate dying ember wrought its ghost upon the floor.

Eagerly I wished the morrow;- vainly I had sought to borrow 

From my books surcease of sorrow-sorrow for the lost Lenore-

For the rare and radiant maiden whom the angels name Lenore-

Nameless here evermore.
